spring:
  ai:
    openai:
      api-key: ""
      chat:
        base-url: "http://localhost:12434/v1"
        options:
          model: "ai/gemma3"
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always

logging:
  level:
    org.springframework.ai: DEBUG